apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: q9l4p22n7-nodejs 
  janus-idp.io/tekton: q9l4p22n7-nodejs
  backstage.io/kubernetes-id: q9l4p22n7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q9l4p22n7-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml