apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q9l4p22n7-nodejs
  janus-idp.io/tekton: q9l4p22n7-nodejs
  backstage.io/kubernetes-id: q9l4p22n7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q9l4p22n7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
